package jogodavelha;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class JogoDaVelha extends javax.swing.JDialog {
    
    public boolean jogadorAtivo = true; // True X, false O
    public int[][] tabuleiro = new int[3][3];
    private javax.swing.JButton[] botoes;

    public JogoDaVelha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Array de Botoes referenciando os botoes gerados pelo GUI Builder;
        botoes = new javax.swing.JButton[] {b1, b2, b3, b4, b5, b6, b7, b8, b9};
        for (javax.swing.JButton botao : botoes) {
            botao.addActionListener(handler); // Associa o mesmo listener a todos os botões
        }
        
        btnRestart.addActionListener(handler);
        
        for (int i = 0; i < 3; i++) {;
            for (int j = 0; j < 3; j++) {
                tabuleiro[i][j] = -1;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRestart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        countX = new javax.swing.JLabel();
        countO = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnRestart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRestart.setText("Reiniciar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("O: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("X: ");

        countX.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        countX.setText("0");

        countO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        countO.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countX))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(countO)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countO))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        b1.setBackground(new java.awt.Color(15, 15, 15));
        b1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b1.setForeground(new java.awt.Color(239, 239, 239));
        b1.setMaximumSize(new java.awt.Dimension(80, 80));
        b1.setMinimumSize(new java.awt.Dimension(80, 80));
        b1.setPreferredSize(new java.awt.Dimension(80, 80));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(15, 15, 15));
        b2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b2.setForeground(new java.awt.Color(239, 239, 239));
        b2.setMaximumSize(new java.awt.Dimension(80, 80));
        b2.setMinimumSize(new java.awt.Dimension(80, 80));
        b2.setPreferredSize(new java.awt.Dimension(80, 80));

        b3.setBackground(new java.awt.Color(15, 15, 15));
        b3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b3.setForeground(new java.awt.Color(239, 239, 239));
        b3.setMaximumSize(new java.awt.Dimension(80, 80));
        b3.setMinimumSize(new java.awt.Dimension(80, 80));
        b3.setPreferredSize(new java.awt.Dimension(80, 80));

        b5.setBackground(new java.awt.Color(15, 15, 15));
        b5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b5.setForeground(new java.awt.Color(239, 239, 239));
        b5.setMaximumSize(new java.awt.Dimension(80, 80));
        b5.setMinimumSize(new java.awt.Dimension(80, 80));
        b5.setPreferredSize(new java.awt.Dimension(80, 80));

        b6.setBackground(new java.awt.Color(15, 15, 15));
        b6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b6.setForeground(new java.awt.Color(239, 239, 239));
        b6.setMaximumSize(new java.awt.Dimension(80, 80));
        b6.setMinimumSize(new java.awt.Dimension(80, 80));
        b6.setPreferredSize(new java.awt.Dimension(80, 80));

        b9.setBackground(new java.awt.Color(15, 15, 15));
        b9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b9.setForeground(new java.awt.Color(239, 239, 239));
        b9.setMaximumSize(new java.awt.Dimension(80, 80));
        b9.setMinimumSize(new java.awt.Dimension(80, 80));
        b9.setPreferredSize(new java.awt.Dimension(80, 80));

        b4.setBackground(new java.awt.Color(15, 15, 15));
        b4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b4.setForeground(new java.awt.Color(239, 239, 239));
        b4.setMaximumSize(new java.awt.Dimension(80, 80));
        b4.setMinimumSize(new java.awt.Dimension(80, 80));
        b4.setPreferredSize(new java.awt.Dimension(80, 80));

        b7.setBackground(new java.awt.Color(15, 15, 15));
        b7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b7.setForeground(new java.awt.Color(239, 239, 239));
        b7.setMaximumSize(new java.awt.Dimension(80, 80));
        b7.setMinimumSize(new java.awt.Dimension(80, 80));
        b7.setPreferredSize(new java.awt.Dimension(80, 80));

        b8.setBackground(new java.awt.Color(15, 15, 15));
        b8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        b8.setForeground(new java.awt.Color(239, 239, 239));
        b8.setMaximumSize(new java.awt.Dimension(80, 80));
        b8.setMinimumSize(new java.awt.Dimension(80, 80));
        b8.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JogoDaVelha dialog = new JogoDaVelha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel countO;
    private javax.swing.JLabel countX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables


    private TrataEventos handler = new TrataEventos();
        

    
    public void exibirVencedor(int jogador) {
        String vencedor = (jogador == 1) ? "X" : "O";
        javax.swing.JOptionPane.showMessageDialog(this, "O jogador " + vencedor + " venceu!");
        if (jogador == 1) {
            countX.setText(Integer.toString(Integer.parseInt(countX.getText())+1));
        } else {
            countO.setText(Integer.toString(Integer.parseInt(countO.getText())+1));
        }
        reiniciar();  // Reinicia o jogo após mostrar a mensagem de vitória
    }

    public void exibirEmpate() {
        javax.swing.JOptionPane.showMessageDialog(this, "O jogo empatou!");
        reiniciar();  // Reinicia o jogo após o empate
    }
    
    public void verificaVitoria() {
        // Verifica Linhas
        for (int i = 0; i < 3; i++) {
            if (tabuleiro[i][0] == tabuleiro[i][1] && tabuleiro[i][1] == tabuleiro[i][2] && tabuleiro[i][0] != -1) {
                exibirVencedor(tabuleiro[i][0]);
                return;
            }
        }

        // Verifica Colunas
        for (int i = 0; i < 3; i++) {
            if (tabuleiro[0][i] == tabuleiro[1][i] && tabuleiro[1][i] == tabuleiro[2][i] && tabuleiro[0][i] != -1) {
                exibirVencedor(tabuleiro[0][i]);
                return;
            }
        }

        // Verifica Diagonais
        if (tabuleiro[0][0] == tabuleiro[1][1] && tabuleiro[1][1] == tabuleiro[2][2] && tabuleiro[0][0] != -1) {
            exibirVencedor(tabuleiro[0][0]);
            return;
        }

        if (tabuleiro[0][2] == tabuleiro[1][1] && tabuleiro[1][1] == tabuleiro[2][0] && tabuleiro[0][2] != -1) {
            exibirVencedor(tabuleiro[0][2]);
            return;
        }

        // Verifica empate
        boolean empate = true;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (tabuleiro[i][j] == -1) {
                    empate = false;
                    break;
                }
            }
        }

        if (empate) {
            exibirEmpate();
        }
    }
    
    public void reiniciar() {
        for (javax.swing.JButton botao : botoes) {
            botao.setText(""); // Limpa o texto do botão
        }

        // Limpa o tabuleiro
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                tabuleiro[i][j] = -1;
            }
        }
    }
    
    public void reiniciarPlacar() {
        countX.setText("0");
        countO.setText("0");
    }
    
    
    private class TrataEventos implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            Object b = e.getSource();
            
            if (b == b1) {
                if (b1.getText() == "") {
                    if (jogadorAtivo) {
                        b1.setText("X");
                        tabuleiro[0][0] = 1; // Marca na matriz o 1 como X
                    } else {
                        b1.setText("O");
                        tabuleiro[0][0] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b2) {
                if (b2.getText() == "") {
                    if (jogadorAtivo) {
                        b2.setText("X");
                        tabuleiro[0][1] = 1; // Marca na matriz o 1 como X
                    } else {
                        b2.setText("O");
                        tabuleiro[0][1] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b3) {
                if (b3.getText() == "") {
                    if (jogadorAtivo) {
                        b3.setText("X");
                        tabuleiro[0][2] = 1; // Marca na matriz o 1 como X
                    } else {
                        b3.setText("O");
                        tabuleiro[0][2] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b4) {
                if (b4.getText() == "") {
                    if (jogadorAtivo) {
                        b4.setText("X");
                        tabuleiro[1][0] = 1; // Marca na matriz o 1 como X
                    } else {
                        b4.setText("O");
                        tabuleiro[1][0] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b5) {
                if (b5.getText() == "") {
                    if (jogadorAtivo) {
                        b5.setText("X");
                        tabuleiro[1][1] = 1; // Marca na matriz o 1 como X
                    } else {
                        b5.setText("O");
                        tabuleiro[1][1] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b6) {
                if (b6.getText() == "") {
                    if (jogadorAtivo) {
                        b6.setText("X");
                        tabuleiro[1][2] = 1; // Marca na matriz o 1 como X
                    } else {
                        b6.setText("O");
                        tabuleiro[1][2] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b7) {
                if (b7.getText() == "") {
                    if (jogadorAtivo) {
                        b7.setText("X");
                        tabuleiro[2][0] = 1; // Marca na matriz o 1 como X
                    } else {
                        b7.setText("O");
                        tabuleiro[2][0] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b8) {
                if (b8.getText() == "") {
                    if (jogadorAtivo) {
                        b8.setText("X");
                        tabuleiro[2][1] = 1; // Marca na matriz o 1 como X
                    } else {
                        b8.setText("O");
                        tabuleiro[2][1] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else if (b == b9) {
                if (b9.getText() == "") {
                    if (jogadorAtivo) {
                        b9.setText("X");
                        tabuleiro[2][2] = 1; // Marca na matriz o 1 como X
                    } else {
                        b9.setText("O");
                        tabuleiro[2][2] = 0; // Marca na matriz o 0 como O
                    }
                    jogadorAtivo = !jogadorAtivo;
                    verificaVitoria();
                }
            } else {
                reiniciar();
                reiniciarPlacar();
            }
        }
    }
}
